name: Backend

on: push

jobs:
  strategy:
    matrix:
      node-version: [14]

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@2
        with:
          node-version: ${{matrix.node-version}}

      - name: Add remote to Heroku
        run: git remote add heroku

      - name: Filter shallow
        run: git filter-branch -- --all

      - name: Deploy heroku
        run: git push heroku main --force
